### ISSUE TITLE
Safari returns en-us instead of en-US

### ISSUE THREAD

**Issue by Phyks** [maxogden/browser-locale#3]
Hi,

As stated [here](https://alicoding.com/localizing-react-app-using-react-router-with-react-intl/) safari behaves incorrectly.

Maybe the following snippet could be added:

```
var locale = navigator.language.split('-')  
locale = locale[1] ? `${locale[0]}-${locale[1].toUpperCase()}` : navigator.language  
```

Thanks

**Comment by zeke** [comment]
Thanks. See https://github.com/maxogden/browser-locale/pull/5
